apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: default
rules:
- apiGroups: ["'","apps","extensions"]
  resources: ["deployments","pods","servcies","secrets","pods/log"]
  verbs: ["get","list","watch","create","update","patch", "delete"]